.*:
  wbits: 'None'
  model_type: 'None'
  groupsize: 'None'
  pre_layer: 0
  mode: 'cai-chat'
  skip_special_tokens: true
  custom_stopping_strings: ''
llama-[0-9]*b-4bit$:
  wbits: 4
  model_type: 'llama'
.*-(4bit|int4)-(gr128|128g):
  wbits: 4
  groupsize: 128
.*-(gr128|128g)-(4bit|int4):
  wbits: 4
  groupsize: 128
.*-3bit-(gr128|128g):
  wbits: 3
  groupsize: 128
.*-(gr128|128g)-3bit:
  wbits: 3
  groupsize: 128
.*(oasst-sft-1-pythia-12b|oasst-sft-6-llama-30b):
  mode: 'instruct'
  instruction_template: 'Open Assistant'
(?!.*v0)(?!.*1.1)(?!.*1_1)(?!.*stable).*vicuna:
  mode: 'instruct'
  instruction_template: 'Vicuna-v0'
.*vicuna.*v0:
  mode: 'instruct'
  instruction_template: 'Vicuna-v0'
.*vicuna.*(1.1|1_1):
  mode: 'instruct'
  instruction_template: 'Vicuna-v1.1'
.*stable.*vicuna:
  mode: 'instruct'
  instruction_template: 'StableVicuna'
.*alpaca:
  mode: 'instruct'
  instruction_template: 'Alpaca'
.*alpaca-native-4bit:
  mode: 'instruct'
  instruction_template: 'Alpaca'
  wbits: 4
  groupsize: 128
.*(galactica|oasst):
  skip_special_tokens: false
.*dolly-v[0-9]-[0-9]*b:
  mode: 'instruct'
  instruction_template: 'Alpaca'
  skip_special_tokens: false
  custom_stopping_strings: '"### End"'
.*koala:
  mode: 'instruct'
  instruction_template: 'Koala'
.*chatglm:
  mode: 'instruct'
  instruction_template: 'ChatGLM'
.*llava:
  mode: 'instruct'
  model_type: 'llama'
  instruction_template: 'LLaVA'
  custom_stopping_strings: '"\n###"'
.*raven:
  mode: 'instruct'
  instruction_template: 'RWKV-Raven'
.*moss-moon.*sft:
  mode: 'instruct'
  instruction_template: 'MOSS'
.*stablelm-tuned:
  mode: 'instruct'
  instruction_template: 'StableLM'
  truncation_length: 4096
  chat_prompt_size: 4096
  chat_prompt_size_max: 4096
.*stablelm-base:
  truncation_length: 4096
  chat_prompt_size: 4096
  chat_prompt_size_max: 4096
.*wizardlm:
  mode: 'instruct'
  model_type: 'llama'
  instruction_template: 'WizardLM'
.*galactica.*finetuned:
  mode: 'instruct'
  instruction_template: 'Galactica Finetuned'
.*galactica.*-v2:
  mode: 'instruct'
  instruction_template: 'Galactica v2'
(?!.*finetuned)(?!.*-v2).*galactica:
  mode: 'instruct'
  instruction_template: 'Galactica'
.*guanaco:
  mode: 'instruct'
  instruction_template: 'Guanaco non-chat'
